<a href="https://colab.research.google.com/github/Sayahniyas/DATASCIENCE_PROJECTS/blob/main/numpy_and_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import numpy as np
arr = np.array([1,2,3,])
print(arr)

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 % arr2)

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(arr1 > arr2)
print(arr1 == arr2)
print(arr1 != arr2)

In [ ]:
arr1 = np.array([[1,2,3],[5,6,7]]) #2 dimentional
arr2 = np.array([[1,2],[5,6],[8,9]])# 3 dimentional array
print(arr1.shape)
print(arr2.shape)

(2, 3)
(3, 2)

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(np.concatenate((arr1,arr2)))

In [ ]:
import numpy as np
arr = np.array([1,2,3,])
print(arr[0])

In [ ]:
#ramdom
import numpy as np
v = np.random.rand(7)
print(v)

[0.49996506 0.34291379 0.1089381  0.592938   0.12402113 0.71101069
 0.3161289 ]

In [ ]:
import numpy as np
arr = np.array( [[[1,2,3],
                [4,5,6],
                [5,8,9]]])
print(arr)
print(arr[0,1,1])

[[[1 2 3]
  [4 5 6]
  [5 8 9]]]
5

In [ ]:
arr1 = np.array([1,2,3,4,5,6,5,8,9])
print(arr1)
arr2 = arr1.reshape(3,3)

print(arr2)

[1 2 3 4 5 6 5 8 9]
[[1 2 3]
 [4 5 6]
 [5 8 9]]

In [ ]:
#pandas(panal data system)

import pandas as pd

> pandas is a open source python libary


1.   used for data cleaning,data analysis,data manipulation and data visualization perperation
2.   working with excel sheets or tabular formate data

pandas data structure



* series
* dataframe

series in a 1 dimentional labled array

In [ ]:
#series
import pandas as pd
marks= pd.Series([55,56,77,88,99,33])
print(marks)

0    55
1    56
2    77
3    88
4    99
5    33
dtype: int64

In [ ]:
import pandas as pd
s1= pd.Series([1,2,3,4],index = ['a','b','c','d'])
print(s1)

a    1
b    2
c    3
d    4
dtype: int64

In [ ]:
import pandas as pd
s1 = pd.Series(["Bca","Bcom","Bca"],index = ["ardra","krishna","hannan"])
print(s1)
print(s1["ardra"])

ardra       Bca
krishna    Bcom
hannan      Bca
dtype: object
Bca

questions:


1. what is numpy and pandas??
: numpy is a python libary thats is used for mathematical operations  pandas are also python libaray that is used for data data analysis,manipulation and data visualization
2. why do we use numpy and pandas? :numpy is used for large mathematical operations where as pandas are used to analize and visualize data  
3. what is series?: one dimetional and labeled array. it displays data with index either given or default  
4. what is the difference between list and numpy array?:
list can hold various datatypes. numpy can only hold one data type and is faster more effiecient than list
5. indexing and slicing?:
6. create a numpy array containing numbes from 1 to 20?
7. create a pandas series with doctors and dept?

In [ ]:
#6
import numpy as np
arr1 = np.arange(1,21)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

In [ ]:
#7
import pandas as pd
s1 = pd.Series(["Dr.shameena","Dr.amal","Dr.husna"], index = ["neurology","pediatrician","surgeon"])
print(s1)

neurology       Dr.shameena
pediatrician        Dr.amal
surgeon            Dr.husna
dtype: object

In [ ]:
import pandas as pd
data = [20,30,40,50]
s=pd.Series(data,index=['a','b','c','d']) #index aka position
print(s)

a    20
b    30
c    40
d    50
dtype: int64

In [ ]:
import pandas as pd
data = {20:"rinza", 30:"sreya", 40:"gayathri", 50:"arya"}  #no need of () and[]
s=pd.Series(data)
print(s)

20       rinza
30       sreya
40    gayathri
50        arya
dtype: object

loc and iloc



iloc default index base

loc manual index base

In [ ]:
data = [10, 20, 30, 40, 50]#no need of () and[]
s=pd.Series(data,index =[1,2,3,4,5])
print(s)

1    10
2    20
3    30
4    40
5    50
dtype: int64

In [ ]:
print(s.loc[1]) #given index
print(s.iloc[1:5]) #default index
print(s.loc[1:3]) # loc doesnot index rule

10
2    20
3    30
4    40
5    50
dtype: int64
1    10
2    20
3    30
dtype: int64

In [ ]:
data = [10,20,30.40]
s=pd.Series(data,index = ['a','b','c'])
print(s[s<30])
print(s.loc['a':'c'])
print(s.iloc[:2])
print(s[s>30])

a    10.0
b    20.0
dtype: float64
a    10.0
b    20.0
c    30.4
dtype: float64
a    10.0
b    20.0
dtype: float64
c    30.4
dtype: float64

In [ ]:
import pandas as pd
sales = pd.Series([1200,850,1500,950,2000],index=['monday','tuesday','wednesday','thursday','friday'])
print(sales)
print(sales.max())
print(sales.min())
print(sales.sum())
print(sales[sales<1000])

monday       1200
tuesday       850
wednesday    1500
thursday      950
friday       2000
dtype: int64
2000
850
6500
tuesday     850
thursday    950
dtype: int64

In [ ]:
#function
import pandas as pd
data = [10, 20, 30,30, 40, 50,50]
s=pd.Series(data)
print(s)
print("with functions:")
print(s.unique()) #remove repeating numbers/data
print(s.nunique()) #return the count of unique data
print(s.value_counts())#how many times a data is repeated

0    10
1    20
2    30
3    30
4    40
5    50
6    50
dtype: int64
with functions:
[10 20 30 40 50]
5
30    2
50    2
10    1
20    1
40    1
Name: count, dtype: int64

In [ ]:
import pandas as pd
data = [10, 20, 30,None, 40, 50,50,None]
s=pd.Series(data)

print(s.isnull())
print(s.notnull())

#what is the diffrence?

0    False
1    False
2    False
3     True
4    False
5    False
6    False
7     True
dtype: bool
0     True
1     True
2     True
3    False
4     True
5     True
6     True
7    False
dtype: bool

In [ ]:
print(s.isna())
print(s.notna())

0    False
1    False
2    False
3     True
4    False
5    False
6    False
7     True
dtype: bool
0     True
1     True
2     True
3    False
4     True
5     True
6     True
7    False
dtype: bool

In [ ]:
print(s.dropna())

0    10.0
1    20.0
2    30.0
4    40.0
5    50.0
6    50.0
dtype: float64

DATAFRAME questions:
1) find the number of students and total marks
2)find the hightest,lowest and average marks
3)find the name of the student with the highest marks
4)check the count of missing values
5)replaceed the missing value with zero
6)find the unique marks and number of unique marks
7)find the student who scored more than 70 marks
8)sort the numbers in decending order

In [ ]:
marks = pd.Series([78,45,67,92,45,56,78,None,34],
                  index = ['anu','rahul','arun','neha','vishnu','diya','akhil','riya','kiran'])
print(marks)

anu       78.0
rahul     45.0
arun      67.0
neha      92.0
vishnu    45.0
diya      56.0
akhil     78.0
riya       NaN
kiran     34.0
dtype: float64
8

In [ ]:
#1) find the number of students and total marks
print(marks.count())
print(marks.sum())

8
495.0

In [ ]:
#2)find the hightest,lowest and average marks
print(marks.max())
print(marks.min())
print(marks.mean())

92.0
34.0
61.875

DATAFRAME

In [ ]:
import pandas as pd
import numpy as np

data = {"name":["arya","rinza","sreya","bob","charlie"],"age":[20,21,22,23,24],"marks":[85,72,np.nan,90,65],"attendence":[95,80,75,np.nan,88],"city":["kochi","delhi","mumbai","kochi","chennai"]}
df = pd.DataFrame(data)
print(df)

      name  age  marks  attendence     city
0     arya   20   85.0        95.0    kochi
1    rinza   21   72.0        80.0    delhi
2    sreya   22    NaN        75.0   mumbai
3      bob   23   90.0         NaN    kochi
4  charlie   24   65.0        88.0  chennai

In [ ]:
#head() and tail() by defult it gives 5 values
print("\t\t\t first 3 numbers\t\t\t")
df.head(3)

			 first 3 numbers

    name  age  marks  attendence    city
0   arya   20   85.0        95.0   kochi
1  rinza   21   72.0        80.0   delhi
2  sreya   22    NaN        75.0  mumbai

In [ ]:
print("\t\t\t last 3 numbers\t\t\t")
df.tail(3)

			 last 3 numbers

      name  age  marks  attendence     city
2    sreya   22    NaN        75.0   mumbai
3      bob   23   90.0         NaN    kochi
4  charlie   24   65.0        88.0  chennai

In [ ]:
#functions in data frame
print(df.shape)
print(df.columns)
print(df.index)
print(df.dtypes)

(5, 5)
Index(['name', 'age', 'marks', 'attendence', 'city'], dtype='object')
RangeIndex(start=0, stop=5, step=1)
name           object
age             int64
marks         float64
attendence    float64
city           object
dtype: object

In [ ]:
#single cloumn
print(df.name)
print(df.marks)
print(df[['name','marks']]) #more than a single row and column

0       arya
1      rinza
2      sreya
3        bob
4    charlie
Name: name, dtype: object
0    85.0
1    72.0
2     NaN
3    90.0
4    65.0
Name: marks, dtype: float64
      name  marks
0     arya   85.0
1    rinza   72.0
2    sreya    NaN
3      bob   90.0
4  charlie   65.0

In [ ]:
print(df)

      name  age  marks  attendence     city
0     arya   20   85.0        95.0    kochi
1    rinza   21   72.0        80.0    delhi
2    sreya   22    NaN        75.0   mumbai
3      bob   23   90.0         NaN    kochi
4  charlie   24   65.0        88.0  chennai

In [50]:
#slicing
#1=iloc()
print(df.iloc[0:3]) #up to 2
#2=loc()
print('\t')
print(df.loc[1:3,['name','marks']]) #full 3 values
print("\t")
print(df.loc[1:3,['attendence','city']])

    name  age  marks  attendence    city
0   arya   20   85.0        95.0   kochi
1  rinza   21   72.0        80.0   delhi
2  sreya   22    NaN        75.0  mumbai

    name  marks
1  rinza   72.0
2  sreya    NaN
3    bob   90.0

   attendence    city
1        80.0   delhi
2        75.0  mumbai
3         NaN   kochi

In [ ]:
#filtering with conditions
print("marks greater than 75:")
print(df[df['marks']>75])
print("\t")
print("\nstudents from kochi:")#\n  newline character tells the interpreter to move the cursor to the beginning of the next line
                                #This effectively creates a line break in the output, making your printed text appear on separate lines.
print(df[df['city']=='kochi'])
print("\t")
print("\nstudents with marks >70 and attendence >80")
print(df[(df['marks']>70) & (df['attendence']>80)]) #use() from multiple arguments in the same line

marks greater than 75:
   name  age  marks  attendence   city
0  arya   20   85.0        95.0  kochi
3   bob   23   90.0         NaN  kochi


students from kochi:
   name  age  marks  attendence   city
0  arya   20   85.0        95.0  kochi
3   bob   23   90.0         NaN  kochi


students with marks >70 and attendence >80
   name  age  marks  attendence   city
0  arya   20   85.0        95.0  kochi

In [57]:
#MATH OPERATIONS
print(df["marks"])
print("\t")
print("\nadd 5")
print(df['marks']+5)
print("\t")
print("\nmarks*2")
print(df['marks'] * 5)
print("\t")
print("\naverage marks")
print(df['marks'].mean)
print("\t")
print("\nmaximun marks")
print(df['marks'].max)
print("\t")
print("\nminimun marks")
print(df['marks'].min)

0    85.0
1    72.0
2     NaN
3    90.0
4    65.0
Name: marks, dtype: float64


add 5
0    90.0
1    77.0
2     NaN
3    95.0
4    70.0
Name: marks, dtype: float64


marks*2
0    425.0
1    360.0
2      NaN
3    450.0
4    325.0
Name: marks, dtype: float64


average marks
<bound method Series.mean of 0    85.0
1    72.0
2     NaN
3    90.0
4    65.0
Name: marks, dtype: float64>


maximun marks
<bound method Series.max of 0    85.0
1    72.0
2     NaN
3    90.0
4    65.0
Name: marks, dtype: float64>


minimun marks
<bound method Series.min of 0    85.0
1    72.0
2     NaN
3    90.0
4    65.0
Name: marks, dtype: float64>

In [59]:
#sorting
print("sort by marks")
print(df.sort_values('marks'))
print("\t.............................\t")
print(df.sort_values('marks',ascending = True))

sort by marks
      name  age  marks  attendence     city
4  charlie   24   65.0        88.0  chennai
1    rinza   21   72.0        80.0    delhi
0     arya   20   85.0        95.0    kochi
3      bob   23   90.0         NaN    kochi
2    sreya   22    NaN        75.0   mumbai
	.............................
      name  age  marks  attendence     city
4  charlie   24   65.0        88.0  chennai
1    rinza   21   72.0        80.0    delhi
0     arya   20   85.0        95.0    kochi
3      bob   23   90.0         NaN    kochi
2    sreya   22    NaN        75.0   mumbai

In [63]:
#rename
df_rename = df.rename(columns = {'marks':"score","attendence":"attendence_percentage"})
print("\t\trenamed dataframe\t\t")
print(df_rename)

		renamed dataframe
      name  age  score  attendence_percentage     city
0     arya   20   85.0                   95.0    kochi
1    rinza   21   72.0                   80.0    delhi
2    sreya   22    NaN                   75.0   mumbai
3      bob   23   90.0                    NaN    kochi
4  charlie   24   65.0                   88.0  chennai

In [69]:
#check for missing value
print(df.isna())
print("\t.................\t")
print(df.isna().sum())
print("\t.................\t")
print(df.notna())
print("\t.................\t")
print("drop nan values")
print(df.dropna())

    name    age  marks  attendence   city
0  False  False  False       False  False
1  False  False  False       False  False
2  False  False   True       False  False
3  False  False  False        True  False
4  False  False  False       False  False
	.................
name          0
age           0
marks         1
attendence    1
city          0
dtype: int64
	.................
   name   age  marks  attendence  city
0  True  True   True        True  True
1  True  True   True        True  True
2  True  True  False        True  True
3  True  True   True       False  True
4  True  True   True        True  True
	.................
drop nan values
      name  age  marks  attendence     city
0     arya   20   85.0        95.0    kochi
1    rinza   21   72.0        80.0    delhi
4  charlie   24   65.0        88.0  chennai

In [74]:
#FORWARD\BACKWARD FILL
df_forward = df.copy()#copy dataframe
df_forward = df_forward.ffill() #syntax
print("\nFORWARD FILL:")
print(df_forward )
print("\t")
print("\t...................\t")
df_backward = df.copy()#copy dataframe
df_backward = df_backward.ffill() #syntax
print("\nBSCKWARD FILL:")
print(df_backward )

FORWARD FILL:
      name  age  marks  attendence     city
0     arya   20   85.0        95.0    kochi
1    rinza   21   72.0        80.0    delhi
2    sreya   22   72.0        75.0   mumbai
3      bob   23   90.0        75.0    kochi
4  charlie   24   65.0        88.0  chennai

	...................

BSCKWARD FILL:
      name  age  marks  attendence     city
0     arya   20   85.0        95.0    kochi
1    rinza   21   72.0        80.0    delhi
2    sreya   22   72.0        75.0   mumbai
3      bob   23   90.0        75.0    kochi
4  charlie   24   65.0        88.0  chennai